name: 'Gcloud version validation'
description: 'Validates and exports the current package.json version against all published service versions existing in a gcloud project.'
author: 'Herbert Hart'
inputs:
  app_yaml_file_path:
    required: true
    description: 'Path to app.yaml file'
  package_json_file_path:
    required: true
    description: 'Path to package.json file'
runs:
  using: 'node12'
  main: 'dist/index.js'
