name: 'Gcloud version validation'
description: 'Validates a given version against existing app engine versions and cancels if it already exists'
author: 'ToastCode'
inputs:
  current_version:
    required: true
    description: 'Current version of the app e.g. 1-0-0'
  app_yaml_file_path:
    required: true
    description: 'Path to app.yaml file'
runs:
  using: 'node12'
  main: 'dist/index.js'
